name: C++ CI MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        compiler: ['g++', 'clang++']

    steps:
    - uses: actions/checkout@v2
    - name: build (${{ matrix.compiler }})
      run: |
        cd ${{ github.workspace }}
        ls
        make v=1 c=${{ matrix.compiler }}
        ls obj
        make clean
    - uses: actions/upload-artifact@v2
      with:
        name: Ubuntu Static (${{ matrix.compiler }})
        path: Primer++